### ISSUE TITLE
allow rainbow parens for parens and brackets

### ISSUE THREAD

**Issue by mikeThurmond** [MrBlobby/swackets#11]
In cljs it is nice to have rainbow parens, brackets, and curly braces.  Is this possible?  Currently I can only choose one or the other (parens and brackets, no curly braces) instead of having all three available (like emacs or cursive rainbow parens)

**Comment by ibraimgm** [comment]
@mikeThurmond, please take a look at the pull request #12. It adds a 'All' option to color brackets, square brackets and parenthesis. Looks good to me.

@jrattray13, IMHO instead of a option list, the settings should use checkboxes for 'Brackets', 'Square brackets' and 'Parenthesis' (I didn't changed it because this would break the configuration of existing users).

I'm also thinking on simplifying how the colors are used (for exemple, I don't think that we really need a 'colors2'; we should simply cycle into 'colors') and add some 'preset colors' (e. g. 'swackets default', 'rainbow-mode', 'custom', etc.)

If you're interested, I'm willing to make these changes and senda new pull request.

**Comment by alexchandel** [comment]
@ibraimgm I agree with checkboxes instead of "All". I don't want them on braces, for example, just Brackets and Parentheses.

**Comment by calebmeyer** [comment]
I think this one can be closed. I just downloaded swackets, and there are options for all three delimiters now.

**Comment by mikeThurmond** [comment]
closing issue, thanks
